// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0-8BdrNEBhzrrTFMztEfwXtNyz0y9Pa0',
    appId: '1:560748377780:web:bb574209411aab539f89e1',
    messagingSenderId: '560748377780',
    projectId: 'breast-cancer-598f2',
    authDomain: 'breast-cancer-598f2.firebaseapp.com',
    storageBucket: 'breast-cancer-598f2.appspot.com',
    measurementId: 'G-MYD9TZ9WE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1S14EdIEwRwp1W780Pp6MmhpSPnKW8iQ',
    appId: '1:560748377780:android:24aab19be7c5b7bd9f89e1',
    messagingSenderId: '560748377780',
    projectId: 'breast-cancer-598f2',
    storageBucket: 'breast-cancer-598f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYPq3DPUJVFGacQOZPnu8nQCdLZpCWTg8',
    appId: '1:560748377780:ios:0ee31532c621f1ea9f89e1',
    messagingSenderId: '560748377780',
    projectId: 'breast-cancer-598f2',
    storageBucket: 'breast-cancer-598f2.appspot.com',
    iosBundleId: 'com.example.breastCancer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYPq3DPUJVFGacQOZPnu8nQCdLZpCWTg8',
    appId: '1:560748377780:ios:0ee31532c621f1ea9f89e1',
    messagingSenderId: '560748377780',
    projectId: 'breast-cancer-598f2',
    storageBucket: 'breast-cancer-598f2.appspot.com',
    iosBundleId: 'com.example.breastCancer',
  );
}
